version: '3.3'

services:
  application:
    image: flavio-image
    container_name: flavio-container-1
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5431/flavio_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qW*RK909
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/openjdk-17/bin:/usr/local/openjdk-17/lib:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/C:/Program Files/Git/bin/
    networks:
      - cloud
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  database:
    image: postgres
    container_name: postgres-container-1
    ports:
      - "5431:5432"
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qW*RK909
      - POSTGRES_DB=flavio_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - cloud
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"


volumes:
  postgres_volume:
    external: true
networks:
  cloud:
    external: true